# Вариант п

+ метод Гаусса с выбором главного элемента
+ метод LU-разложения (если применим)
+ метод Якоби
+ метод Зейделя
+ метод верхней релаксации
+ *Метод градиентного спуска
+ *Метод минимальных невязок
+ *Стабилизированный метод бисопряженных градиентов

In [31]:
import numpy as np

In [32]:
epsilon = 1e-14

In [33]:
A = np.zeros((100, 100))
f = np.array([1 / (i + 1) for i in range(100)])

A[0][0] = 10.0 + 1
A[0][1] = 1.0

for i in range(1, 99):
    A[i][i - 1] = 1.0
    A[i][i] = 10.0 + i + 1
    A[i][i + 1] = 1.0

A[99][0] = 1.0
A[99][99] = 1.0

for i in range(1, 99):
    A[99][i] = 2.0

# new_A = np.zeros((100, 100))
# new_f = np.zeros(100)

# for i in range(100):
#     for j in range(100):
#         for k in range(100):
#             new_A[i][j] += A[i][k] * A[k][j]
#         new_f[i] += A[i][j] * f[j]

# A = new_A
# f = new_f

E = np.zeros((100, 100))
D = np.zeros((100, 100))
F = np.zeros((100, 100))

for i in range(100):
    for j in range(100):
        if j < i:
            E[i][j] = A[i][j]
        elif j > i:
            F[i][j] = A[i][j]
        else:
            D[i][j] = A[i][j]

print("A:")
print(A)
print("E:")
print(E)
print("D:")
print(D)
print("F:")
print(F)
print("f:")
print(f)

A:
[[ 11.   1.   0. ...   0.   0.   0.]
 [  1.  12.   1. ...   0.   0.   0.]
 [  0.   1.  13. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ... 108.   1.   0.]
 [  0.   0.   0. ...   1. 109.   1.]
 [  1.   2.   2. ...   2.   2.   1.]]
E:
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [1. 2. 2. ... 2. 2. 0.]]
D:
[[ 11.   0.   0. ...   0.   0.   0.]
 [  0.  12.   0. ...   0.   0.   0.]
 [  0.   0.  13. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ... 108.   0.   0.]
 [  0.   0.   0. ...   0. 109.   0.]
 [  0.   0.   0. ...   0.   0.   1.]]
F:
[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]
f:
[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333
 0.07692308 0.07142857 0.06666667 0.0625     0.05882353 0.05555556
 0.05263158 0.05

## Решим систему методом Якоби

In [34]:
x_old = np.array([0.0 for _ in range(100)])

iterations = 0

while np.max(np.abs(A @ x_old - f)) >= epsilon:
    x_new = np.zeros(100)
    for i in range(100):
        for j in range(100):
            if i == j:
                continue
            x_new[i] = x_new[i] + A[i][j] * x_old[j]
        x_new[i] = (f[i] - x_new[i]) / A[i][i]
    x_old = x_new
    iterations += 1

print(f"Number of iterations: {iterations}")
print(f"x = {x_new}")
print(A @ x_new - f)

Number of iterations: 19
x = [ 8.79538292e-02  3.25078785e-02  2.19516293e-02  1.54542741e-02
  1.16885328e-02  9.21773371e-03  7.49439444e-03  6.23470370e-03
  5.28093893e-03  4.53856775e-03  3.94770604e-03  3.46869629e-03
  3.07430886e-03  2.74527689e-03  2.46761725e-03  2.23095850e-03
  2.02746175e-03  1.85110376e-03  1.69718855e-03  1.56200718e-03
  1.44259607e-03  1.33656231e-03  1.24195537e-03  1.15717146e-03
  1.08088150e-03  1.01197596e-03  9.49522399e-04  8.92732321e-04
  8.40935102e-04  7.93557303e-04  7.50106125e-04  7.10156087e-04
  6.73338210e-04  6.39331190e-04  6.07854150e-04  5.78660650e-04
  5.51533717e-04  5.26281688e-04  5.02734735e-04  4.80741930e-04
  4.60168763e-04  4.40895038e-04  4.22813071e-04  4.05826156e-04
  3.89847241e-04  3.74797793e-04  3.60606807e-04  3.47209960e-04
  3.34548863e-04  3.22570415e-04  3.11226238e-04  3.00472179e-04
  2.90267873e-04  2.80576358e-04  2.71363738e-04  2.62598878e-04
  2.54253144e-04  2.46300156e-04  2.38715586e-04  2.31476965e

# Рещим систему методом Зейделя

In [35]:
x_old = np.array([0.0 for _ in range(100)])

iterations = 0

while np.max(np.abs(A @ x_old - f)) >= epsilon:
    x_new = np.zeros(100)
    for i in range(100):
        sigma = 0
        for j in range(i):
            sigma = sigma + A[i][j] * x_new[j]
        for j in range(i + 1, 100):
            sigma = sigma + A[i][j] * x_old[j]
        x_new[i] = (f[i] - sigma) / A[i][i]
    x_old = x_new
    iterations += 1

print(f"Number of iterations: {iterations}")
print(f"x = {x_new}")
print(A @ x_new - f)

Number of iterations: 11
x = [ 8.79538292e-02  3.25078785e-02  2.19516293e-02  1.54542741e-02
  1.16885328e-02  9.21773371e-03  7.49439444e-03  6.23470370e-03
  5.28093893e-03  4.53856775e-03  3.94770604e-03  3.46869629e-03
  3.07430886e-03  2.74527689e-03  2.46761725e-03  2.23095850e-03
  2.02746175e-03  1.85110376e-03  1.69718855e-03  1.56200718e-03
  1.44259607e-03  1.33656231e-03  1.24195537e-03  1.15717146e-03
  1.08088150e-03  1.01197596e-03  9.49522399e-04  8.92732321e-04
  8.40935102e-04  7.93557303e-04  7.50106125e-04  7.10156087e-04
  6.73338210e-04  6.39331190e-04  6.07854150e-04  5.78660650e-04
  5.51533717e-04  5.26281688e-04  5.02734735e-04  4.80741930e-04
  4.60168763e-04  4.40895038e-04  4.22813071e-04  4.05826156e-04
  3.89847241e-04  3.74797793e-04  3.60606807e-04  3.47209960e-04
  3.34548863e-04  3.22570415e-04  3.11226238e-04  3.00472179e-04
  2.90267873e-04  2.80576358e-04  2.71363738e-04  2.62598878e-04
  2.54253144e-04  2.46300156e-04  2.38715586e-04  2.31476965e